### ISSUE TITLE
JVM crashes during indexing document with NaN text

### ISSUE THREAD

**Issue by wangxieric** [terrier-org/pyterrier#42] opened 2020-07-02 10:58 UTC
Issue: The JVM will crash if the 'text' is NaN.
Example solutions: The system can throw one exception or convert the NaN text into an empty string or something reasonable.

**Comment by cmacdonald** [comment] 2020-07-02 11:00
Just to be clear, this is for DFIndexer or IterDictIndexer?

Also, you said you had a solution?

**Comment by wangxieric** [comment] 2020-07-02 11:04
IterDictIndexer for sure. However, the DFIndexer crashes also but its reason is not confirmed, which might also caused by the big dataset.

I addressed the problem for IterDictIndexer as follows:
`def isNaN(num):
      return num != num

def antique_doc_iter():
     for index, row in queries.iterrows():
           if index % 100000 == 0:
                 print(f'processing document {index} ', datetime.now())
           if isNaN(row['text']):
                 yield {'docno': row['docno'], 'text': ""}
           else:
                 yield {'docno': row['docno'], 'text': row['text']}`

**Comment by cmacdonald** [comment] 2020-07-02 11:18
Stack trace you showed me for DFIndexer makes it certain:
```
J 1701 c2 java.io.StringReader.<init>(Ljava/lang/String;)V java.base@11.0.6 (28 bytes) @ 0x00007f482489e7f7 [0x00007f482489e6a0+0x0000000000000157]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x884d59]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x3b9
V  [libjvm.so+0x907094]  jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) [clone .constprop.190]+0x204
V  [libjvm.so+0x90735f]  jni_NewObjectA+0xff
```

**Comment by cmacdonald** [comment] 2020-07-02 11:24
I have made a fix for the DFIndexer - Xi can you check it when you have a chance?; I will have to think more about the IterDictIndexer., which uses FlatJSONDcoument internally.

**Comment by cmacdonald** [comment] 2020-07-05 11:06
Could you have been sending a number instead of a string?

**Comment by cmacdonald** [comment] 2020-10-02 12:42
Closing as cannot reproduce.

**Closed by cmacdonald** 2020-10-02 12:42 UTC
